- name: Install Helm
  ansible.builtin.import_role:
    name: geerlingguy.helm

- name: Install Helm diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    plugin_version: "{{ helm_diff_version }}"
  become: false
