{{- if .Values.pgbouncerRead.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "humansignals.fullname" . }}-pgbouncer-read
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
   {{- range $key, $value := .Values.pgbouncerRead.service.annotations }}
     {{ $key }}: {{ $value | quote }}
   {{- end }}
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
spec:
  type: {{ .Values.pgbouncerRead.service.type }}
  ports:
  - name: {{ template "humansignals.fullname" . }}-pgbouncer-read
    port: 6543
    targetPort: 6543
  selector:
    app: {{ template "humansignals.fullname" . }}
    role: pgbouncer-read
{{- end }}
