{{- if and .Values.pgbouncerRead.enabled .Values.pgbouncerRead.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "humansignals.fullname" . }}-pgbouncer-read
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "humansignals.fullname" . }}-pgbouncer-read
  minReplicas: {{ .Values.pgbouncerRead.hpa.minpods }}
  maxReplicas: {{ .Values.pgbouncerRead.hpa.maxpods }}
  metrics:
  {{- with .Values.pgbouncerRead.hpa.cputhreshold }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  behavior:
    {{ toYaml .Values.pgbouncerRead.hpa.behavior | nindent 4 }}
{{- end }}
