{{ if .Values.plugins.enabled }}
    {{- if or .Values.pluginsIngestion.enabled .Values.pluginsExports.enabled .Values.pluginsJobs.enabled .Values.pluginsScheduler.enabled }} 
      {{- required (printf (include "snippet.error-on-invalid-values-template" .)
        "plugins*.enabled cannot be set if plugins.enabled is true" ""
      ) nil -}}
    {{- end -}}

    {{ $mode := "" }}
    {{ if .Values.pluginsAsync.enabled }}
        {{ $mode = "ingestion" }}
    {{ end }}
    
    {{ include "plugins-deployment" ( dict "root" . "params" .Values.plugins "name" "plugins" "mode" $mode ) }}
{{ end }}
