{{- if (include "humansignals.redis.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "humansignals.redis.secretName" . }}
type: Opaque
data:
  {{ template "humansignals.redis.secretPasswordKey" . }}: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}
