{{- if (include "humansignals.clickhouse.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "humansignals.clickhouse.secretName" . }}
type: Opaque
data:
  {{ template "humansignals.clickhouse.secretPasswordKey" . }}: {{ .Values.externalClickhouse.password | b64enc | quote }}
{{- end }}
