{{- if (include "humansignals.postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "humansignals.postgresql.secretName" . }}
type: Opaque
data:
  {{ template "humansignals.postgresql.secretPasswordKey" . }}: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
