- name: Install CRI-O
  ansible.builtin.import_role:
    name: ktooi.crio

- name: Add CNI plugins
  become: yes
  ansible.builtin.apt:
    name: containernetworking-plugins
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Add CNI plugins
  become: yes
  ansible.builtin.dnf:
    name: containernetworking-plugins
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Add CRI-O config
  ansible.builtin.template:
    src: 02-crio.conf
    dest: /etc/crio/crio.conf.d/02-crio.conf
    mode: 0644
  notify:
    - Restart CRI-O

- name: Ensure handlers are notified now to avoid unspecified behavior
  ansible.builtin.meta: flush_handlers

- name: Install crictl
  ansible.builtin.import_role:
    name: darkwizard242.crictl
