- name: Install conntrack
  ansible.builtin.apt:
    name: conntrack
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install conntrack
  ansible.builtin.dnf:
    name: conntrack-tools
    state: latest
  become: true
  when: ansible_facts['os_family'] == "RedHat"
