- name: Install conntrack
  become: yes
  ansible.builtin.apt:
    name: conntrack
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Install conntrack
  become: yes
  ansible.builtin.dnf:
    name: conntrack-tools
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
