- name: Upgrade system
  become: yes
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Upgrade system
  become: yes
  ansible.builtin.dnf:
    name: "*"
    state: latest
    autoremove: true
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"
