production: false

server:
  host: humansignals-sda.ivolga.tech

grafana:
  enabled: true
  host: grafana.humansignals-sda.ivolga.tech

clickhouse:
  internal: true
  host:
  cluster:
  database:
  user:
  password:
  # Whether to use TLS connection
  secure: true
  # Whether to verify TLS certificate
  verify: true
