production: false

server:
  host: humansignals-sda.ivolga.tech

grafana:
  enabled: true
  host: grafana.humansignals-sda.ivolga.tech

kafka:
  # Enable non-TLS external access to an internal Kafka
  # The external port would be 9094 for the Kafka Clients
  externalAccess: false

clickhouse:
  internal: true
  # If you require non-TLS external access to an internal ClickHouse, use LoadBalancer. Otherwise, use ClusterIP
  # The external ports would be 8123 for the HTTP API and 9000 for the Native Protocol
  serviceType: ClusterIP
  host:
  cluster:
  database:
  user:
  password:
  # Whether to use TLS connection
  secure: true
  # Whether to verify TLS certificate
  verify: true
