- name: Install HumanSignals
  kubernetes.core.helm:
    chart_ref: oci://ghcr.io/ivolga-tech/humansignals-devops/helm/humansignals
    chart_version: 30.0.0
    create_namespace: yes
    release_name: humansignals
    release_namespace: humansignals
    release_values: "{{ lookup('ansible.builtin.template', 'values.yaml') | ansible.builtin.from_yaml }}"
    timeout: 30m
    wait: yes

- name: Allow nginx to use X-Forwarded-* headers
  kubernetes.core.k8s:
    state: patched
    kind: ConfigMap
    name: ingress-nginx-controller
    namespace: ingress-nginx
    resource_definition:
      data:
        use-forwarded-headers: "true"

- name: Get a HumanSignals Ingress
  kubernetes.core.k8s_info:
    kind: Ingress
    name: humansignals
    namespace: humansignals
  register: humansignals_ingress

- name: Create HumanSignals Ingress IP fact for Caddy
  ansible.builtin.set_fact:
    humansignals_ingress_ip: "{{ humansignals_ingress.resources[0].status.loadBalancer.ingress[0].ip }}"
