- name: Install HumanSignals
  kubernetes.core.helm:
    chart_ref: oci://ghcr.io/ivolga-tech/humansignals-devops/helm/humansignals
    chart_version: 30.0.0
    release_name: humansignals
    release_namespace: humansignals
    release_values: "{{ lookup('ansible.builtin.template', 'values.yaml') | ansible.builtin.from_yaml }}"
    create_namespace: yes
    wait: yes
