- name: Allow nginx to use X-Forwarded-* headers
  kubernetes.core.k8s:
    state: patched
    kind: ConfigMap
    name: ingress-nginx-controller
    namespace: ingress-nginx
    resource_definition:
      data:
        use-forwarded-headers: "true"
