{
 "title": "ClickHouse (cluster overview)",
 "tags": [
  "HumanSignals",
  "ClickHouse"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Max node uptime in the cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ClickHouseAsyncMetrics_Uptime{})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Number of executing queries.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ClickHouseMetrics_Query{})" }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ClickHouseMetrics_VersionInteger)"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (shard) (ClickHouseMetrics_VersionInteger))"
    }
   ]
  },
  {
   "title": "Nodes count",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "count(ClickHouseMetrics_VersionInteger)",
     "legendFormat": "Nodes count"
    }
   ]
  },
  {
   "title": "Nodes uptime",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_Uptime{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "description": "Number of executing queries.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ClickHouseMetrics_Query{}", "legendFormat": "{{pod}}" },
    { "expr": "sum(ClickHouseMetrics_Query{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Failed queries",
   "type": "timeseries",
   "description": "Number of failed queries.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_FailedQuery{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(ClickHouseProfileEvents_FailedQuery{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Slow reads",
   "type": "timeseries",
   "description": "Number of reads from a file that were slow. This indicate system overload.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_SlowRead{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Distributed Connection Errors",
   "type": "timeseries",
   "description": "Show Distributed server-server connections failures",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{}[$__rate_interval])",
     "legendFormat": "DistributedConnectionFailAtAll {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailTry{}[$__rate_interval])",
     "legendFormat": "ClickHouseProfileEvents_DistributedConnectionFailTry {{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of connections to TCP server (clients with native interface), also included server-server distributed query connections & number of connections to HTTP server",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection",
     "legendFormat": "TCP - {{pod}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection",
     "legendFormat": "HTTP - {{pod}}"
    }
   ]
  },
  {
   "title": "Replication and ZooKeeper Exceptions",
   "type": "timeseries",
   "description": "Show readonly and partial shutdown replicas, zookeeer exceptions, zookeeer sessions, zookeeper init requests",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReadonlyReplica",
     "legendFormat": "ReadonlyReplica {{instance}}"
    },
    {
     "expr": "increase(ClickHouseProfileEvents_ReplicaPartialShutdown{}[$__rate_interval])",
     "legendFormat": "ReplicaPartialShutdown {{label_name}}"
    }
   ]
  },
  {
   "title": "Replication queue jobs",
   "type": "timeseries",
   "description": "Show how intensive data exchange between replicas in parts.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxQueueSize{}",
     "legendFormat": "ReplicasMaxQueueSize {{pod}}"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedChecks{}",
     "legendFormat": "ReplicatedChecks {{pod}}"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedFetch{}",
     "legendFormat": "ReplicatedFetch {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedSend{}",
     "legendFormat": "ReplicatedSend {{instance}}"
    }
   ]
  },
  {
   "title": "Read backoff",
   "type": "timeseries",
   "description": "Number of times the number of query processing threads was lowered due to slow reads.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_ReadBackoff{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Zookeeper requests",
   "type": "timeseries",
   "description": "Number of in flight requests to ZooKeeper.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperRequest",
     "legendFormat": "ReadonlyReplica {{instance}}"
    }
   ]
  },
  {
   "title": "Max replica delay",
   "type": "timeseries",
   "description": "Show seconds when replicated servers can be delayed relative to current time,  when you insert directly in *ReplicatedMegreTree table on one server clickhouse need time to replicate new parts of data to another servers in same shard in background",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxAbsoluteDelay{}",
     "legendFormat": "ReplicasMaxAbsoluteDelay {{pod}}"
    }
   ]
  },
  {
   "title": "Disk size available",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_DiskTotal_default - ClickHouseAsyncMetrics_DiskUsed_default",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Parts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active parts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "targets": [
    { "expr": "ClickHouseMetrics_PartsActive", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Outdated parts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsOutdated",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max parts count for partition",
   "type": "timeseries",
   "description": "Each logical partition defined over `PARTITION BY` contains few physical data \"parts\" ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_MaxPartCountForPartition",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Merges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Merges",
   "type": "timeseries",
   "description": "Number of launched background merges.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Merge{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merged rows",
   "type": "timeseries",
   "description": "Rows read for background merges. This is the number of rows before merge.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MergedRows{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merged bytes",
   "type": "timeseries",
   "description": "Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MergedUncompressedBytes{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Replicated part fetches",
   "type": "timeseries",
   "description": "Number of times a data part was downloaded from replica of a ReplicatedMergeTree table.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetches{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicated part fetches of merged",
   "type": "timeseries",
   "description": "Number of times we prefer to download already merged part from replica of ReplicatedMergeTree table instead of performing a merge ourself (usually we prefer doing a merge ourself to save network traffic). This happens when we have not all source parts to perform a merge or when the data part is old enough.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicated failed part fetches",
   "type": "timeseries",
   "description": "Number of times a data part was failed to download from replica of a ReplicatedMergeTree table.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicated part merges",
   "type": "timeseries",
   "description": "Number of times data parts of ReplicatedMergeTree tables were successfully merged.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMerges{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicated part data loss",
   "type": "timeseries",
   "description": "Number of times a data part that we wanted doesn't exist on any replica (even on replicas that are offline right now). That data parts are definitely lost. This is normal due to asynchronous replication (if quorum inserts were not enabled), when the replica on which the data part was written was failed and when it became online after fail it doesn't contain that data part.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedDataLoss{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Background Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Buffer Flush Schedule Pool",
   "type": "timeseries",
   "description": "BufferFlushSchedulePoolTask: number of active tasks in BackgroundBufferFlushSchedulePool. This pool is used for periodic Buffer flushes.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundBufferFlushSchedulePoolTask",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Common Pool",
   "type": "timeseries",
   "description": "CommonPoolTask: number of active tasks in an associated background pool.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundCommonPoolTask",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed Schedule Pool ",
   "type": "timeseries",
   "description": "DistributedSchedulePoolTask: number of active tasks in BackgroundDistributedSchedulePool. This pool is used for distributed sends that is done in background.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundDistributedSchedulePoolTask",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Background Fetches Pool",
   "type": "timeseries",
   "description": "FetchesPoolTask: number of active fetches in an associated background pool.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundFetchesPoolTask",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merges And Mutations Pool",
   "type": "timeseries",
   "description": "MergesAndMutationsPoolTask: number of active merges and mutations in an associated background pool",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundMergesAndMutationsPoolTask",
     "legendFormat": "MergesAndMutationsPoolTask {{instance}}"
    }
   ]
  },
  {
   "title": "Message Broker Schedule Pool",
   "type": "timeseries",
   "description": "MessageBrokerSchedulePoolTask: number of active tasks in BackgroundProcessingPool for message streaming",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundMessageBrokerSchedulePoolTask",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Move Pool",
   "type": "timeseries",
   "description": "MovePoolTask: number of active tasks in BackgroundProcessingPool for moves",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundMovePoolTask",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schedule Pool",
   "type": "timeseries",
   "description": "SchedulePoolTask: number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundSchedulePoolTask",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SELECT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SELECT queries",
   "type": "timeseries",
   "description": "Number of executing SELECT queries.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_SelectQuery{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(ClickHouseProfileEvents_SelectQuery{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Bytes SELECTed",
   "type": "timeseries",
   "description": "Number of bytes selected",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_SelectedBytes{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(ClickHouseProfileEvents_SelectedBytes{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failed SELECT queries",
   "type": "timeseries",
   "description": "Number of failed SELECT queries.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_FailedSelectQuery{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(ClickHouseProfileEvents_FailedSelectQuery{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "INSERT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "INSERT queries",
   "type": "timeseries",
   "description": "Number of executing INSERT queries.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_InsertQuery{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(ClickHouseProfileEvents_InsertQuery{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Bytes INSERTed",
   "type": "timeseries",
   "description": "Number of bytes inserted",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_InsertedBytes{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(ClickHouseProfileEvents_InsertedBytes{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failed INSERT queries",
   "type": "timeseries",
   "description": "Number of failed INSERT queries.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_FailedInsertQuery{}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(ClickHouseProfileEvents_FailedInsertQuery{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mutations (ALTER DELETE/ALTER UPDATE)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "Mutations",
   "type": "timeseries",
   "description": "Number of mutations (ALTER DELETE/UPDATE).",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ClickHouseMetrics_PartMutation", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}