{
 "title": "Kubernetes deployment",
 "tags": [
  "HumanSignals",
  "Kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{}, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage / Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n* sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[2m]))\n/ sum(kube_pod_container_resource_requests{resource=~\"cpu\", namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\", container!~\"POD|\"})"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\", container!~\"POD|\"}) / sum (kube_pod_container_resource_requests{resource=~\"memory\", namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\", container!~\"POD|\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[2m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=~\"cpu\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=~\"cpu\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"})"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\", container!~\"POD|\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=~\"memory\", namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\", container!~\"POD|\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=~\"memory\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"})"
    }
   ]
  },
  {
   "title": "Replica status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"^$namespace$\", deployment=~\"^$deployment\"})",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"^$namespace$\",deployment=~\"^$deployment\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"^$namespace$\",deployment=~\"^$deployment\"})",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "CPU throttled",
   "type": "timeseries",
   "description": "Percentage of CPU periods where the container ran but was throttled (stopped from running the whole CPU period).",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100\n* sum by(pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[1m]))\n/ sum by(pod, namespace) (increase(container_cpu_cfs_periods_total{namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\"}[2m]))",
     "legendFormat": "IN"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\"}[2m]))",
     "legendFormat": "OUT"
    }
   ]
  }
 ]
}