{
 "title": "Loki",
 "tags": [
  "HumanSignals",
  "Loki"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_request_duration_seconds_count{app_kubernetes_io_component=\"read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"}[$__rate_interval]))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, route) (loki_request_duration_seconds_bucket{app_kubernetes_io_component=\"read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{ route }} 99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le,route) (loki_request_duration_seconds_bucket{app_kubernetes_io_component=\"read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{ route }} 50th Percentile"
    }
   ]
  },
  {
   "title": "BoltDB Shipper - QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_boltdb_shipper_request_duration_seconds_count{app_kubernetes_io_component=\"read\", operation=\"Shipper.Query\"}[$__rate_interval]))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "BoltDB Shipper - Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{app_kubernetes_io_component=\"read\", operation=\"Shipper.Query\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{app_kubernetes_io_component=\"read\", operation=\"Shipper.Query\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Error log rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate({app=\"humansignals-loki\", component=\"read\"} | logfmt | level=\"error\"[1m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "logs",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"humansignals-loki\", component=\"read\"} | logfmt | level=\"error\"",
     "legendFormat": "Rate"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_request_duration_seconds_count{app_kubernetes_io_component=\"write\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"}[$__rate_interval]))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, route) (loki_request_duration_seconds_bucket{app_kubernetes_io_component=\"write\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"}))",
     "legendFormat": "{{ route }} 99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le,route) (loki_request_duration_seconds_bucket{app_kubernetes_io_component=\"write\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"}))",
     "legendFormat": "{{ route }} 50th Percentile"
    }
   ]
  },
  {
   "title": "BoltDB Shipper - QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_boltdb_shipper_request_duration_seconds_count{app_kubernetes_io_component=\"write\", operation=\"WRITE\"}[$__rate_interval]))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "BoltDB Shipper - Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{app_kubernetes_io_component=\"write\", operation=\"WRITE\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{app_kubernetes_io_component=\"write\", operation=\"WRITE\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Error log rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate({app=\"humansignals-loki\", component=\"write\"} | logfmt | level=\"error\"[1m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "logs",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "{app=\"humansignals-loki\", component=\"write\"} | logfmt | level=\"error\"",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Lines received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{}[$__rate_interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  }
 ]
}