{
 "title": "PgBouncer",
 "tags": [
  "HumanSignals",
  "PgBouncer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_pooled_total{}[$__rate_interval]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Query time (p50)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_duration_seconds_total{}[$__rate_interval])) /\nsum(rate(pgbouncer_stats_queries_pooled_total{}[$__rate_interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Client connections used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * \n\n(\n    sum by (pod) (pgbouncer_used_clients) +\n    sum by (pod) (pgbouncer_login_clients) \n)\n\n/ \n\n(\n    sum by (pod)(pgbouncer_used_clients) + \n    sum by (pod)(pgbouncer_free_clients) + \n    sum by (pod)(pgbouncer_login_clients)\n) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Servers connections used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (pod)(pgbouncer_used_servers) \n\n/ \n(\n    sum by (pod)(pgbouncer_used_servers) + \n    sum by (pod)(pgbouncer_free_servers)\n) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod(s) count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(pgbouncer_version_info{})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Client connections by state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_client_active_connections)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(pgbouncer_pools_client_waiting_connections)",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Server connections by state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_server_active_connections)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(pgbouncer_pools_server_idle_connections)",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(pgbouncer_pools_server_used_connections)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod)(rate(pgbouncer_stats_sql_transactions_pooled_total{}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client connections free",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 10 },
   "targets": [
    { "expr": "pgbouncer_free_clients", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Server connections used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 10 },
   "targets": [
    { "expr": "pgbouncer_used_servers", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}