{
 "title": "Redis",
 "tags": [
  "HumanSignals",
  "Redis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{}[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{} / redis_memory_max_bytes{}"
    }
   ]
  },
  {
   "title": "Hits / Misses per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{}[$interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{}[$interval])",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Commands per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(redis_commands_processed_total{}[$interval])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients{}" }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes{}", "legendFormat": "Used" },
    { "expr": "redis_memory_max_bytes{} ", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Networking",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(redis_net_input_bytes_total{}[$interval])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(redis_net_output_bytes_total{}[$interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "redis_connected_clients{}", "legendFormat": "Connected" },
    { "expr": "redis_blocked_clients{}", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "Total items (db0)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "redis_db_keys{db=\"db0\"}",
     "legendFormat": "Items"
    }
   ]
  },
  {
   "title": "Top commands (by QPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (cmd) (irate(redis_commands_total{}[$interval])))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Top commands (by cumulative latency)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, sum by (cmd) (irate(redis_commands_duration_seconds_total{}[$interval])))",
     "legendFormat": "{{instance}} {{cmd}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{}[$interval])) by (addr)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{}[$interval])) by (addr)",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Expiring / Not-Expiring keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum (redis_db_keys{}) - sum (redis_db_keys_expiring{}) ",
     "legendFormat": "Not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{}) ",
     "legendFormat": "Expiring"
    }
   ]
  }
 ]
}