{
 "title": "Session recordings",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "humansignals-events replica status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=\"humansignals\", deployment=\"humansignals-events\"})",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"humansignals\",deployment=\"humansignals-events\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"humansignals\",deployment=\"humansignals-events\"})",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "/s/ success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{status!~\"5.*\", path=~\"/s/?\"}[2m]\n      )\n   )\n/ \n\nsum(\n  rate(\n    nginx_ingress_controller_requests{path=~\"/s/?\"}[2m]\n      )\n    )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/s/ requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{path=\"/e/\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/s/ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status!=\"404\", status!=\"500\", path=~\"/s/?\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status!=\"404\", status!=\"500\", path=~\"/s/?\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status!=\"404\", status!=\"500\", path=~\"/s/?\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "NGINX logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\"} |= `POST /s/` | json"
    }
   ]
  },
  {
   "title": "humansignals-events ERRORs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{container=\"humansignals-events\", level=\"error\"} | json"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "humansignals-recordings-ingestion replica status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=\"humansignals\", deployment=\"humansignals-recordings-ingestion\"})",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"humansignals\",deployment=\"humansignals-recordings-ingestion\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"humansignals\",deployment=\"humansignals-recordings-ingestion\"})",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Message byte size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(consumed_message_size_bytes_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Message batch size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(consumed_batch_size_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Topic production/consumption rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=\"session_recording_events\"}[5m])/5)",
     "legendFormat": "produced"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=\"session_recording_events\", consumergroup=\"session-recordings\"}[5m])/5)",
     "legendFormat": "consumed"
    }
   ]
  },
  {
   "title": "Consumer group lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"session_recording_events\", consumergroup=\"session-recordings\"})",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Consumption time lag seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(time() * 1000 - (max(latest_processed_timestamp_ms{groupId=\"session-recordings\",topic=\"session_recording_events\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{container=\"humansignals-recordings-ingestion\"} | json"
    }
   ]
  }
 ]
}