- name: Install HumanSignals and its dependencies
  hosts: all
  become: true
  roles:
    - role: common
      become: false

    - role: crio
      vars:
        crio_version: "1.25"
        crictl_version: 1.25.0

    - role: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_users:
          - "{{ ansible_user }}"

    - role: minikube

    - role: helm
      vars:
        helm_version: v3.12.0
        helm_diff_version: v3.8.0

    - role: humansignals
      become: false
      tags: humansignals

    - role: jupyterhub
      become: false
      tags: jupyterhub
      when: jupyterhub.enabled
