- name: Install HumanSignals and its dependencies
  hosts: all
  become: true
  roles:
    - role: common
      become: false

    - role: crio
      vars:
        crio_version: "1.25"
        crictl_version: 1.25.0

    - role: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_users:
          - "{{ ansible_user }}"

    - role: minikube

    - role: geerlingguy.helm
      vars:
        helm_version: v3.11.1

    - role: humansignals
      become: false
      tags: humansignals
