roles:
  - name: ktooi.crio
    version: 1.2.1
  - name: darkwizard242.crictl
    version: 2.3.0
  - name: geerlingguy.docker
    version: 6.1.0
  - name: gantsign.minikube
    version: 1.34.0
  - name: geerlingguy.helm
    version: master

collections:
  - name: kubernetes.core
    version: 2.4.0
