ingress:
  hostname: "{{ server.host }}"

clickhouse:
  enabled: {{ clickhouse.external }}

{% if not clickhouse.external %}
externalClickhouse:
  host: {{ clickhouse.host }}
  cluster: {{ clickhouse.cluster }}
  database: {{ clickhouse.database }}
  user: {{ clickhouse.user }}
  password: {{ clickhouse.password }}
  secure: true
  verify: true
{% endif %}
