cert-manager:
  enabled: true

ingress:
  hostname: "{{ server.host }}"
{% if production %}
  letsencrypt: true
{% endif %}
  nginx:
    enabled: true

ingress-nginx:
  controller:
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: single-pool

clickhouse:
  enabled: {{ clickhouse.internal }}

{% if not clickhouse.internal %}
env:
  - name: KAFKA_URL_FOR_CLICKHOUSE
    value: "kafka://{{ ansible_host }}:30000"

kafka:
  externalAccess:
    enabled: true
    service:
      type: NodePort
      nodePorts:
        - 30000

externalClickhouse:
  host: "{{ clickhouse.host }}"
  cluster: "{{ clickhouse.cluster }}"
  database: "{{ clickhouse.database }}"
  user: "{{ clickhouse.user }}"
  password: "{{ clickhouse.password }}"
  secure: {{ clickhouse.secure }}
  verify: {{ clickhouse.verify }}
{% endif %}
