web:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8001"

cert-manager:
  enabled: {{ production }}

ingress:
  hostname: "{{ server.host }}"
  letsencrypt: {{ production }}
  nginx:
    enabled: true

ingress-nginx:
  controller:
    ingressClassResource:
      default: true
    metrics:
      enabled: {{ grafana.enabled }}
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: single-pool

{% if kafka.externalAccess or (not clickhouse.internal) %}
kafka:
  externalAccess:
    enabled: true
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: single-pool
      loadBalancerIPs:
        - "{{ ipify_public_ip }}"
{% endif %}

clickhouse:
  enabled: {{ clickhouse.internal }}
  serviceType: "{{ clickhouse.serviceType }}"
  settings:
    prometheus/endpoint: "/metrics"
    prometheus/port: "9363"
    prometheus/metrics: "true"
    prometheus/events: "true"
    prometheus/asynchronous_metrics: "true"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9363"

{% if not clickhouse.internal %}
env:
  - name: KAFKA_URL_FOR_CLICKHOUSE
    value: "kafka://{{ ipify_public_ip }}:9094"

externalClickhouse:
  host: "{{ clickhouse.host }}"
  cluster: "{{ clickhouse.cluster }}"
  database: "{{ clickhouse.database }}"
  user: "{{ clickhouse.user }}"
  password: "{{ clickhouse.password }}"
  secure: {{ clickhouse.secure }}
  verify: {{ clickhouse.verify }}
{% endif %}

grafana:
  enabled: {{ grafana.enabled }}
  ingress:
    enabled: {{ grafana.enabled }}
    hosts:
      - "{{ grafana.host }}"
{% if production %}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: nginx-letsencrypt-grafana-humansignals
        hosts:
          - "{{ grafana.host }}"
{% endif %}

prometheus:
  enabled: true

prometheus-kafka-exporter:
  enabled: true

prometheus-postgres-exporter:
  enabled: true

prometheus-redis-exporter:
  enabled: true
