- name: Install Caddy
  ansible.builtin.import_role:
    name: caddy_ansible.caddy_ansible
  vars:
    caddy_user: caddy
    caddy_systemd_capabilities_enabled: yes
    caddy_config: "{{ lookup('ansible.builtin.template', 'Caddyfile') }}"
