apiVersion: v2
name: humansignals
description: 🦔 HumanSignals is developer-friendly, open-source product analytics.
kubeVersion: ">= 1.23-0 <= 1.25-0"
home: https://humansignals.ru
sources:
  - https://github.com/ivolga-tech/humansignals-devops

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 30.0.0+patch3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.42.0

dependencies:
  - name: cert-manager
    version: 1.6.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

  - name: ingress-nginx
    version: 4.0.13
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.nginx.enabled

  - name: kafka
    version: 14.9.3
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: kafka.enabled

  - name: minio
    version: 11.3.5
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: minio.enabled

  - name: postgresql
    version: 8.6.1
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: postgresql.enabled

  - name: redis
    version: 16.8.9
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: redis.enabled

  - name: zookeeper
    version: 7.0.5
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: zookeeper.enabled

  # Monitoring & observability
  - name: grafana
    version: 6.40.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

  - name: loki
    version: 3.3.4
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled

  - name: promtail
    version: 6.6.2
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled

  - name: prometheus
    version: 15.10.4
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  - name: prometheus-kafka-exporter
    version: 1.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-kafka-exporter.enabled

  - name: prometheus-postgres-exporter
    version: 4.4.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-postgres-exporter.enabled

  - name: prometheus-redis-exporter
    version: 5.3.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-redis-exporter.enabled

  - name: prometheus-statsd-exporter
    version: 0.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-statsd-exporter.enabled

maintainers:
  - name: grantral
    email: grantral@pm.me
