[book]
title = "HumanSignals Documentation"
authors = ["grantral"]
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/ivolga-tech/humansignals-devops/tree/main/docs"
edit-url-template = "https://github.com/ivolga-tech/humansignals-devops/edit/main/docs/{path}"
site-url = "/docs/"
