proxy:
  service:
    type: ClusterIP

ingress:
  enabled: true
  hosts:
    - "{{ jupyterhub.host }}"
{% if production %}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: nginx-letsencrypt-jupyter-humansignals
      hosts:
        - "{{ jupyterhub.host }}"
{% endif %}

hub:
  config:
    Authenticator:
      admin_users:
        - "{{ jupyterhub.user }}"
      allowed_users:
        - "{{ jupyterhub.user }}"
    DummyAuthenticator:
      password: "{{ jupyterhub.password }}"
    JupyterHub:
      authenticator_class: dummy
